########################################
# Constants
########################################

uint8 command
string task_name
string robot_type
string repo_id
string task_instruction
uint8 frequency
uint8 episode_time
uint8 episode_num
uint8 warmup_time
uint8 reset_time
bool push_to_hub
bool private_mode
bool use_image_buffer

# command
uint8 NONE = 0
uint8 START_RECORD = 1
uint8 START_INFERENCE = 2
uint8 STOP = 3
uint8 MOVE_TO_NEXT = 4
uint8 RERECORD = 5
uint8 TERMINATE_ALL = 6
---
bool success
string message